import { Box, styled, Button, Card, Stack, Dialog, Typography } from '@mui/material';
import { LoadingButton } from '@mui/lab';

export default {
    PageWrapper: styled(Box)(({ theme }) => ({
        // height: '100vh',
        minHeight: '100vh',
        overflowY: 'auto',
        position: 'relative',
        backgroundColor: 'black',
    })),
    GridWrapper: styled(Box)(({ theme }) =>
        theme.unstable_sx({
            marginTop: { xs: '48rem', md: '32rem', lg: '23.5rem' },
            marginX: 'auto',
            paddingX: '5px',
            position: 'absolute',
            left: 0,
            right: 0,
            zIndex: 10,
            display: 'block',
            maxWidth: { xs: `calc(100vw - 4rem)`, md: 'auto' },
        }),
    ),
    BackgroundImg: styled(Box)(({ theme }) => ({
        position: 'absolute',
        top: 0,
        right: 0,
        zIndex: 1,
        width: '100%',
        height: '100%',
        backgroundImage: "url('/backgroundImg.jpg')",
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        filter: `invert(0.9)`,
    })),
    BackgroundFilter: styled(Box)(({ theme }) => ({
        position: 'fixed',
        top: 0,
        right: 0,
        zIndex: 2,
        display: 'block',
        width: '100vw',
        height: '100vh',
        backgroundRepeat: 'no-repeat',
        backgroundSize: 'cover',
        backgroundColor: 'rgba(38, 117, 131,0.7)',
    })),
    ActionButtonContainer: styled('div')(({ theme }) => ({
        marginTop: '1rem',
        display: 'flex',
        justifyContent: 'flex-end',
        gap: '0.8rem',
    })),
    ActionButton: styled(LoadingButton)(({ theme }) => ({
        padding: '4px 10px 4px 10px',
        backgroundColor: theme.palette.primary.main,
        color: theme.palette.common.black,
        borderRadius: '2rem',
    })),
    ModalContent: styled('div')(({ theme }) => ({})),
    ModalMessageContainer: styled(Button)(({ theme }) => ({
        display: 'flex',
        gap: '0.5rem',
        alignItems: 'center',
    })),
    SwitchCointainer: styled(Stack)(({ theme }) => ({
        position: 'fixed',
        zIndex: 10,
        display: 'flex',
        gap: '3px',
        alignItems: 'center',
        justifyContent: 'flex-end',
        width: '100%',
        flexDirection: 'row',
    })),
    UserDetailHeader: styled(Stack)(({ theme }) => ({
        position: 'absolute',
        zIndex: 10,
        display: 'flex',
        gap: '3px',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        flexDirection: 'row',
    })),
    SwitchCard: styled(Card)(({ theme }) => ({
        display: 'flex',
        gap: '3px',
        alignItems: 'center',
        backgroundColor: 'rgba(255,255,255,0.45)',
        borderRadius: '2rem',
        padding: '0.4rem',
        margin: '1rem',
        '&:hover': {
            opacity: 0.8,
        },
    })),
    UserDetailCardContainer: styled(Stack)(({ theme }) =>
        theme.unstable_sx({
            marginTop: '5rem',
            position: 'absolute',
            left: 0,
            right: 0,
            zIndex: 10,
            marginX: 'auto',
            display: 'block',
            maxWidth: { xs: `calc(100vw - 2rem)`, md: 'auto' },
        }),
    ),
};
